version: '3.9'

services:
  php-apache-debian:
    image: php:8.1-apache
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html

  php-apache-centos:
    image: naqoda/centos-apache-php
    ports:
      - "8090:80"
    volumes:
      - ./src:/var/www/app/public_html
