version: '3.9'

services:
  php-apache-debian:
    image: php:8.1-apache
    ports:
      - "9016:80"
    volumes:
      - ./src:/var/www/html

  php-apache-centos:
    image: identicum/centos-apache-php
    ports:
      - "9018:80"
    volumes:
      - ./src:/var/www/app/public_html
      - ./src:/var/www/html
