version: '3.9'

services:
  db:
    image: mariadb:10.5.9
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 's3cr3t'
      MYSQL_USER: 'username'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'mydb'
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=s3cr3t
      interval: 5s
      retries: 5

  db_admin:
    image: phpmyadmin/phpmyadmin:5
    ports:
      - '8081:80'
    environment:
      - PMA_HOST=db
      - PMA_ABSOLUTE_URI=http://localhost:8001/
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - db_admin_data:/var/www/html

  app:
    build:
      context: .
      dockerfile: docker/php8-mysql-xdebug/Dockerfile
    ports:
      - '8080:80'
    working_dir: /var/www/html
    volumes:
      - ./docker/php8-mysql-xdebug/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./src:/var/www/html
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
  db_admin_data: